### ISSUE TITLE
Support sympy `latex_mode="equation"`

### ISSUE THREAD

**Issue by gutow** [gutow/Algebra_with_Sympy#22]
Hey

First of all thank you !

I just stumbled across algebra_with_sympy due to my post on [Stackoverflow](https://stackoverflow.com/questions/76967456/proper-workflow-for-storing-symbols-and-expressions/76969598#76969598), and it fits my workflow nearly perfect as I'm having similar tasks to do in my structural engineering profession. Especially the Eqn- class is amazing, which speeds up the calculation process drastically compared to regular sympy.

Nontheless I usually use [Quarto ](https://quarto.org/)to convert my Notebooks to readable PDFs wich enabled me to crossrefence between images and equations, set imagecaptions and so on. With sympy i was able to use `sp.init_printing(use_latex='mathjax', latex_mode='equation')` which then produced numbered equations in the latex export. Importing your package leads to overwrite this setting. Is it possible that you add the `latex_mode='equation'`.

_Originally posted by @PascalGitz in https://github.com/gutow/Algebra_with_Sympy/discussions/6#discussioncomment-6813953_

**Comment by gutow** [comment]
I think that can be incorporated. Do you have ideas on how you would like it to work. I am setting up courseware today, but will try to look at it and provide some suggestions about how controlling this could work over the next couple of days.

**Comment by PascalGitz** [comment]
First of all I'm lacking a lot of programming skills to actually understand what is going on in your package and in sympy :) But wouldn't it be convenient to only use your package for the Eqn class and let the rest of the printing etc be done by regular sympy? As far as I can tell you did your latex_override to add the equation labeling?


The most obvious for me would be the same as it can be done in sympy. Define the expected output in the `sp.init_printing(use_latex='mathjax', latex_mode='equation')` at the start of the notebook

**Comment by gutow** [comment]
> But wouldn't it be convenient to only use your package for the Eqn class and let the rest of the printing etc be done by regular sympy? 

As much as possible I am trying to do that.

> As far as I can tell you did your latex_override to add the equation labeling?

Unfortunately, to support human readable equations in many different environments (command line, ipython terminal and jupyter notebooks), I have to do more fiddling than just the equation labeling. To get an idea of the kinds of output things that can be adjusted and are special to this package see:

- https://gutow.github.io/Algebra_with_Sympy/algebra_with_sympy.html#convenience-tools-and-defaults-for-interactive-use-of-sympy
- https://gutow.github.io/Algebra_with_Sympy/algebra_with_sympy.html#controlling-the-format-of-interactive-outputs
- https://gutow.github.io/Algebra_with_Sympy/Demonstration%20of%20equation%20class.html#Output-options

**Comment by gutow** [comment]
I am trying to understand what would be ideal for you. There are a couple of possibilities, I can think of:
* Add a switch to force all outputs to be formatted as latex equations (pretty much equivalent to your code snippet and what `init_printing(use_latex='mathjax', latex_mode='equation')` does. I may even be able to set things up to respect that and  other `init_printing` calls.
* If you want to play nice with Quarto, I could also have a switch that would tag the name you gave to the equation at the end of the equation `$$ {#eq-stddev}` as suggested [here](https://quarto.org/docs/get-started/authoring/jupyter.html#cross-references). Is this what you are doing manually?

Other details to consider would be whether to have this set `algwsym.config.output.labels = False` when it is invoked. For interactive use, I have found my students are less confused if they are reminded of the name used for the equation. However, since we cannot just use "(1), (2) ..." this does not look like what would be found in a formal paper or text. Am I correct that you are using Quarto to automate some of the formal latex document generation?

Once I understand how you want to use these features, I can figure out what all the options are that can be integrated with what the software currently does. I also want to make sure that I keep basic usage as simple as possible.

**Comment by gutow** [comment]
> I am trying to understand what would be ideal for you. There are a couple of possibilities, I can think of:
> 
>     * Add a switch to force all outputs to be formatted as latex equations (pretty much equivalent to your code snippet and what `init_printing(use_latex='mathjax', latex_mode='equation')` does. I may even be able to set things up to respect that and  other `init_printing` calls.
> 
>     * If you want to play nice with Quarto, I could also have a switch that would tag the name you gave to the equation at the end of the equation `$$ {#eq-stddev}` as suggested [here](https://quarto.org/docs/get-started/authoring/jupyter.html#cross-references). Is this what you are doing manually?

* Another possibility is to support [LaTeX labeling and cross-referencing directly](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing). I am not sure how this behaves when rendering notebooks.

**Comment by PascalGitz** [comment]
Hey

I guess we are on the same page:

> * If you want to play nice with Quarto, I could also have a switch that would tag the name you gave to the equation at the end of the equation `$$ {#eq-stddev}` as suggested [here](https://quarto.org/docs/get-started/authoring/jupyter.html#cross-references). Is this what you are doing manually?

Currently I'm not labeling the sympy generated equations, so i cannot reference them. I mostly created the basic equations in markdown with the label, and then did further calculations in sympy.  So that switch would be highly appreciated.


> * Add a switch to force all outputs to be formatted as latex equations (pretty much equivalent to your code snippet and what `init_printing(use_latex='mathjax', latex_mode='equation')` does. I may even be able to set things up to respect that and  other `init_printing` calls.

This switch would be ideal. Switching between **equation / inline** and **labeled (includes numbering)/ no number**. How does this behave in the notebook rendering? I already had problems with your  equation labeling in the notebook.

> Other details to consider would be whether to have this set `algwsym.config.output.labels = False` when it is invoked. For interactive use, I have found my students are less confused if they are reminded of the name used for the equation. However, since we cannot just use "(1), (2) ..." this does not look like what would be found in a formal paper or text. Am I correct that you are using Quarto to automate some of the formal latex document generation?

I assume that if that gets invoked as False, i could still use the `init_printing(use_latex='mathjax', latex_mode='equation')` which I prefer. And if I want your automatic equation labeling i would then use your printer / renderer. 

I do not change anything in the latex code that gets generated by Quarto, so I use Quarto for the whole process of document generation.

**Comment by gutow** [comment]
> I do not change anything in the latex code that gets generated by Quarto, so I use Quarto for the whole process of document generation.

I think we may actually be envisioning something very different. I will set up an instance of Quarto to play with. Could you provide a link to a simple .ipynb the illustrates how you are using it in Quarto. This would allow me to better understand things. I fear that I am misunderstanding how you are using Quarto and what is possible inside it.

**Comment by PascalGitz** [comment]
Ah okay, i added you as a collaborator to one of my repos, where I use the Quarto book structure. It is a bit loaded, but I will create a simple example ASAP.

**Comment by gutow** [comment]
> Ah okay, i added you as a collaborator to one of my repos, where I use the Quarto book structure. It is a bit loaded, but I will create a simple example ASAP.

Danke. I am out of practice reading German and never spoke it well. Am I right that these are mostly engineering examples?

**Comment by PascalGitz** [comment]
Yes, those are exclusively engineering examples. 
Would you still prefer a less loaded example?

**Comment by gutow** [comment]
> Would you still prefer a less loaded example?

Let me get Quarto set up and try one that you already have. This may take me a while, as I am fitting this in among coordinating the launch of a large class that starts next week. I will let you know if I have questions or need a simpler example.

**Comment by gutow** [comment]
I have made a little headway in wrapping my mind around what you are trying to do. This is where I am so far:
* If I understand how Quarto works, my idea of generating results from code cells that will get automatically numbered if they are just left as the result of the code cell, will not work.
* I have started to look at the operations you have added for your convenience in sympycalc.
   * I particularly like your automatic substitution of a dictionary/list of values into an equation to calculate a bunch of results. I am used to doing this with large data sets so usually take the formula and use it with Pandas.
   * I note that in render.py you use `Eq()` rather than `Eqn()`. I assume this is your way of accessing the default equation output as `$$ the latex of the equation $$` so that you can copy directly into your markdown cells. I think that is workable as long as you do not generate an equality that Sympy can evaluate to `True`. Am I understanding this correctly?
   * I have not completely figured out how you are using sympycalc, but note that you have not included the part of Algebra_with_Sympy that overrides many of the sympy operations to make them `Eqn()` aware. Without that you may encounter unexpected behavior and errors.

I need to dig a little more and try things, but I think a setting that gives you equations in the `$$ \begin...\end{equation}$$` format to facilitate copy and paste may be the best option. I am not seeing a way to automate more of this.

**Comment by PascalGitz** [comment]
> * note that in render.py you use `Eq()` rather than `Eqn()`. I assume this is your way of accessing the default equation output as `$$ the latex of the equation $$` so that you can copy directly into your markdown cells. I think that is workable as long as you do not generate an equality that Sympy can evaluate to `True`. Am I understanding this correctly?

I stumbled upon your Eqn class after I created my 90% of my book. In the last chapters I use the Eqn class which is more convenient than my approach in render.py. 

> * I have not completely figured out how you are using sympycalc, but note that you have not included the part of Algebra_with_Sympy that overrides many of the sympy operations to make them `Eqn()` aware. Without that you may encounter unexpected behavior and errors.

Thank you for the warning, I'm currently testing it. 
I was aiming to use your Eqn class without your preset printing options.

Overall I conclude that my Issue is solved if you could add a switch to have the printing options set to False, meaning I can use the settings from the `sympy.init_printing`. Automated equation labeling would be nice to have, but not necessary.

**Comment by gutow** [comment]
@PascalGitz 
I apologize for the long wait, but I think I have something that maintains the ability to switch things on and off and does what you want. I still need to write unit tests for it, but you can try it by pulling down this branch: https://github.com/gutow/Algebra_with_Sympy/tree/Format-as-latex-equation.

To format output as equations set `algwsym_config.output.latex_as_equations = True`. To revert set this to `False`.

If you try it let me know how it works.

**Comment by PascalGitz** [comment]
Hey @gutow 

Thank you for working on it. 

I couldn't get this branch running, I do get some errors cloning it. 


``
error: invalid path 'Developer Testing/how does is play with solve?.ipynb'
``

**Comment by gutow** [comment]
> Hey @gutow
> 
> Thank you for working on it.
> 
> I couldn't get this branch running, I do get some errors cloning it.
> 
> `error: invalid path 'Developer Testing/how does is play with solve?.ipynb'`

@PascalGitz Sorry about that. That looks like an issue with .gitignore. I will investigate, but probably not for a few days.

**Comment by gutow** [comment]
> > Hey @gutow
> > Thank you for working on it.
> > I couldn't get this branch running, I do get some errors cloning it.
> > `error: invalid path 'Developer Testing/how does is play with solve?.ipynb'`
> 
> @PascalGitz Sorry about that. That looks like an issue with .gitignore. I will investigate, but probably not for a few days.

@PascalGitz I do not know why you saw the error. Github shows the file in the expected directory: https://github.com/gutow/Algebra_with_Sympy/tree/Format-as-latex-equation/Developer%20Testing. If your pull of the branch did not bring it down, try downloading it manually. You could also ignore the error. The testing notebooks do not impact the functioning of the software.

**Comment by gutow** [comment]
> error: invalid path 'Developer Testing/how does is play with solve?.ipynb'

@PascalGitz I had another thought. Are you using an OS that does not handle spaces in paths well? If so, you may have to work around that in some way that removes the spaces in my path names.

**Comment by PascalGitz** [comment]
Hey @gutow 

Thank you for the input, I will give it a shot as soon as I have time for it.

**Comment by gutow** [comment]
@PascalGitz Just so you know, I have included the fix to Algebra_with_SymPy that I believe meets your requirements in the latest V1.0.0 release. You should be able to install it via pip: `pip install -U Algebra_with_Sympy`.

**Comment by PascalGitz** [comment]
Thank you for incorporating it.
The approach, as shown in the following snippet, cannot be rendered in LaTeX. But it works fine in the Jupyternotebook.

```
$$
\\begin{equation}\\frac{a}{b}=c\\end{equation}
$$
```

**Comment by gutow** [comment]
> Thank you for incorporating it. The approach, as shown in the following snippet, cannot be rendered in LaTeX. But it works fine in the Jupyternotebook.
> 
> ```
> $$
> \\begin{equation}\\frac{a}{b}=c\\end{equation}
> $$
> ```

@PascalGitz I set it up to generate Latex that renders properly in Jupyter notebooks. Because of the way strings are processed in the notebook backslashes need to be escaped with an extra backslash to appear in the notebook. I may be able to do some fancy footwork with Python raw strings to fix this. However, I need to know what situations should provide output with single rather than doubled backslashes. Can you provide some direction on that? If you can, please open a new issue with the information.
